export const FETCH_MEDICOS_ACTUANTES = 'FETCH_MEDICOS_ACTUANTES';
export const FETCH_MEDICOS_SOLICITANTES = 'FETCH_MEDICOS_SOLICITANTES';
export const LOAD_MEDICOS_ACTUANTES = 'LOAD_MEDICOS_ACTUANTES';
export const LOAD_MEDICOS_SOLICITANTES = 'LOAD_MEDICOS_SOLICITANTES';
export const LOAD_MEDICOS_ACTUANTES_ERROR = 'LOAD_MEDICOS_ACTUANTES_ERROR';
export const LOAD_MEDICOS_SOLICITANTES_ERROR = 'LOAD_MEDICOS_SOLICITANTES_ERROR';
