export const FETCH_COMPROBANTES_PAGO = 'FETCH_COMPROBANTES_PAGO';
export const LOAD_COMPROBANTES_PAGO = 'LOAD_COMPROBANTES_PAGO';
export const LOAD_COMPROBANTES_PAGO_ERROR = 'LOAD_COMPROBANTES_PAGO_ERROR';
