export const FETCH_COMPROBANTES_PAGO = 'FETCH_COMPROBANTES_PAGO';
export const LOAD_COMPROBANTES_PAGO = 'LOAD_COMPROBANTES_PAGO';
export const LOAD_COMPROBANTES_PAGO_ERROR = 'LOAD_COMPROBANTES_PAGO_ERROR';
export const FETCH_COMPROBANTES_LISTA = 'FETCH_COMPROBANTES_LISTA';
export const LOAD_COMPROBANTES_LISTA_SUCCESS = 'LOAD_COMPROBANTES_LISTA_SUCCESS';
export const LOAD_COMPROBANTES_LISTA_FAILED = 'LOAD_COMPROBANTES_LISTA_FAILED';
