export const ID_TIPO_COMPROBANTE_FACTURA = 1;
export const ID_TIPO_COMPROBANTE_LIQUIDACION = 2;
export const ID_TIPO_COMPROBANTE_NOTA_DE_DEBITO = 3;
export const ID_TIPO_COMPROBANTE_NOTA_DE_CREDITO = 4;
export const ID_TIPO_COMPROBANTE_FACTURA_CREDITO_ELECTRONICA = 5;
export const ID_TIPO_COMPROBANTE_NOTA_DE_DEBITO_ELECTRONICA = 6;
export const ID_TIPO_COMPROBANTE_NOTA_DE_CREDITO_ELECTRONICA = 7;
