export const FETCH_CANTIDAD_TURNOS = 'FETCH_CANTIDAD_TURNOS';
export const FETCH_CANTIDAD_TURNOS_SUCCESS = 'FETCH_CANTIDAD_TURNOS';
export const FETCH_CANTIDAD_TURNOS_FAILED = 'FETCH_CANTIDAD_TURNOS';
