export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const SET_AUTHORIZATION_TOKEN = 'SET_AUTHORIZATION_TOKEN';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT = 'LOGOUT';
export const ELEGIR_SUCURSAL = 'ELEGIR_SUCURSAL';
