export const FETCH_PRESENTACIONES_OBRA_SOCIAL = 'FETCH_PRESENTACIONES_OBRA_SOCIAL';
export const LOAD_PRESENTACIONES_OBRA_SOCIAL = 'LOAD_PRESENTACIONES_OBRA_SOCIAL';
export const LOAD_PRESENTACIONES_OBRA_SOCIAL_ERROR = 'LOAD_PRESENTACIONES_OBRA_SOCIAL_ERROR';
export const ABRIR_PRESENTACION = 'ABRIR_PRESENTACION';
export const LOAD_PRESENTACION_ABIERTA = 'LOAD_PRESENTACION_ABIERTA';
