export const FETCH_PRESENTACIONES_OBRA_SOCIAL = 'FETCH_PRESENTACIONES_OBRA_SOCIAL';
export const LOAD_PRESENTACIONES_OBRA_SOCIAL = 'LOAD_PRESENTACIONES_OBRA_SOCIAL';
export const LOAD_PRESENTACIONES_OBRA_SOCIAL_ERROR = 'LOAD_PRESENTACIONES_OBRA_SOCIAL_ERROR';
export const ABRIR_PRESENTACION = 'ABRIR_PRESENTACION';
export const CERRAR_PRESENTACION = 'CERRAR_PRESENTACION';
export const FINALIZAR_PRESENTACION = 'FINALIZAR_PRESENTACION';
export const LOAD_PRESENTACION_DETAIL_ID = 'LOAD_PRESENTACION_DETAIL_ID';
export const LOAD_PRESENTACION_OBRA_SOCIAL_ID = 'LOAD_PRESENTACION_OBRA_SOCIAL_ID';
