export const FETCH_PRESENTACIONES_OBRA_SOCIAL = 'FETCH_PRESENTACIONES_OBRA_SOCIAL';
export const LOAD_PRESENTACIONES_OBRA_SOCIAL = 'LOAD_PRESENTACIONES_OBRA_SOCIAL';
export const LOAD_PRESENTACIONES_OBRA_SOCIAL_ERROR = 'LOAD_PRESENTACIONES_OBRA_SOCIAL_ERROR';
