export const FETCH_MOVIMIENTOS_CAJA = 'FETCH_MOVIMIENTOS_CAJA';
export const LOAD_MOVIMIENTOS_CAJA = 'LOAD_MOVIMIENTOS_CAJA';
export const LOAD_MOVIMIENTOS_CAJA_ERROR = 'LOAD_MOVIMIENTOS_CAJA_ERROR';
