export const FETCH_PACIENTES = 'FETCH_PACIENTES';
export const LOAD_PACIENTES = 'LOAD_PACIENTES';
export const LOAD_PACIENTES_ERROR = 'LOAD_PACIENTES_ERROR';
export const DELETE_PACIENTES = 'DELETE_PACIENTES';
