export const FETCH_OBRAS_SOCIALES = 'FETCH_OBRAS_SOCIALES';
export const LOAD_OBRAS_SOCIALES = 'LOAD_OBRAS_SOCIALES';
export const LOAD_OBRAS_SOCIALES_ERROR = 'LOAD_OBRAS_SOCIALES_ERROR';
export const DELETE_OBRAS_SOCIALES = 'DELETE_OBRAS_SOCIALES';
