export const FETCH_ESTUDIOS_SIN_PRESENTAR_OBRA_SOCIAL = 'FETCH_ESTUDIOS_SIN_PRESENTAR_OBRA_SOCIAL';
export const LOAD_ESTUDIOS_SIN_PRESENTAR_OBRA_SOCIAL = 'LOAD_ESTUDIOS_SIN_PRESENTAR_OBRA_SOCIAL';
export const LOAD_ESTUDIOS_SIN_PRESENTAR_OBRA_SOCIAL_ERROR = 'LOAD_ESTUDIOS_SIN_PRESENTAR_OBRA_SOCIAL_ERROR';
export const FINALIZAR_PRESENTACION_OBRA_SOCIAL = 'FINALIZAR_PRESENTACION_OBRA_SOCIAL';
export const LOAD_DATE_VALUE = 'LOAD_DATE_VALUE';
export const LOAD_PRESENTACION_DETAIL_ID = 'LOAD_PRESENTACION_DETAIL_ID';
export const ACTUALIZAR_INPUT_VALUE = 'ACTUALIZAR_INPUT_VALUE';
export const ELIMINAR_FILA = 'ELIMINAR_FILA';
