export const FETCH_ESTUDIOS_SIN_PRESENTAR_OBRA_SOCIAL = 'FETCH_ESTUDIOS_SIN_PRESENTAR_OBRA_SOCIAL';
export const LOAD_ESTUDIOS_SIN_PRESENTAR_OBRA_SOCIAL = 'LOAD_ESTUDIOS_SIN_PRESENTAR_OBRA_SOCIAL';
export const LOAD_ESTUDIOS_SIN_PRESENTAR_OBRA_SOCIAL_ERROR = 'LOAD_ESTUDIOS_SIN_PRESENTAR_OBRA_SOCIAL_ERROR';
export const FINALIZAR_PRESENTACION_OBRA_SOCIAL = 'FINALIZAR_PRESENTACION_OBRA_SOCIAL';
export const LOAD_PRESENTACION_DETAIL_ID = 'LOAD_PRESENTACION_DETAIL_ID';
export const ACTUALIZAR_NRO_DE_ORDEN = 'ACTUALIZAR_NRO_DE_ORDEN';
export const ACTUALIZAR_IMPORTE = 'ACTUALIZAR_IMPORTE';
export const ACTUALIZAR_ANESTESISTA = 'ACTUALIZAR_ANESTESISTA';
export const ACTUALIZAR_DIF_PACIENTE = 'ACTUALIZAR_DIF_PACIENTE';
export const ACTUALIZAR_PENSION = 'ACTUALIZAR_PENSION';
export const ELIMINAR_FILA = 'ELIMINAR_FILA';

