export const FETCH_PAGO_ANESTESISTA = 'FETCH_PAGO_ANESTESISTA';
export const FETCH_ANESTESISTAS = 'FETCH_ANESTESISTAS';
export const LOAD_ANESTESISTAS = 'LOAD_ANESTESISTAS';
export const LOAD_ANESTESISTAS_ERROR = 'LOAD_ANESTESISTAS_ERROR';
export const LOAD_PAGO_ANESTESISTA = 'LOAD_PAGO_ANESTESISTA';
export const CANCEL_PAGO_ANESTESISTA = 'CANCEL_PAGO_ANESTESISTA';

