export const REFACTURAR_ESTUDIO = 'REFACTURAR_ESTUDIO';
export const REFACTURAR_ESTUDIO_SUCCESS = 'REFACTURAR_ESTUDIO_SUCCESS';
export const REFACTURAR_ESTUDIO_FAILED = 'REFACTURAR_ESTUDIO_FAILED';
export const FETCH_DATOS_DE_UNA_PRESENTACION = 'FETCH_DATOS_DE_UNA_PRESENTACION';
export const FETCH_DATOS_DE_UNA_PRESENTACION_SUCCESS = 'FETCH_DATOS_DE_UNA_PRESENTACION_SUCCESS';
export const FETCH_DATOS_DE_UNA_PRESENTACION_FAILED = 'FETCH_DATOS_DE_UNA_PRESENTACION_FAILED';
