name: Cypress Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  setup:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
    steps:
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install system dependencies
        run: |
          sudo apt-get -y install libpq-dev libjpeg-dev
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          repository: cedir/web
          path: web
      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r web/requirements.txt
      - name: Setup settings
        run: |
          cp web/settings.py.bak web/settings.py
          mkdir logs cache
      - name: Migrate
        run: |
          python web/manage.py migrate
          python web/manage.py loaddata web/fixtures/*.json
      - name: Create user for testing
        run: |
          python web/manage.py shell -c "from django.contrib.auth.models import User; User.objects.create_user('asd', 'asd@asd.com', 'asd')"
      - name: Checkout uli
        uses: actions/checkout@v2
        with:
          path: uli
      - name: Setup settings
        run: |
          cp uli/src/js/app/config.js.bak uli/src/js/app/config.js
          cp uli/cypress.json.bak uli/cypress.json
          mkdir uli/logs uli/cache
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm start, python ../web/manage.py runserver
          browser: chrome
          wait-on: 'http://localhost:8000, http://localhost:3000'
          working-directory: uli
