name: E2E tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SUPER_SECRET_USER: ${{ secrets.SuperSecretUser }}
      SUPER_SECRET_PASS: ${{ secrets.SuperSecretPass }}
    steps:
      - uses: actions/checkout@v2
      - name: Copy settings
        run: |
          cp src/js/app/config.js.bak src/js/app/config.js
          cp cypress.json.bak cypress.json
      - name: Adding user for testing
        run: |
          sed -i 's/usuario/"$SUPER_SECRET_USER"/' cypress.json 
          sed -i 's/password/"$SUPER_SECRET_PASS"/' cypress.json
      - name: Update base url
        run: |
          sed -i 's/http/https/' src/js/app/config.js
          sed -i 's/127.0.0.1:8000/staging.cedir.com.ar/' src/js/app/config.js
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          browser: chrome
          wait-on: 'http://localhost:3000'
